/**
 * GET /.well-known/agent-card.json
 *
 * A2A discovery endpoint. Returns the AgentCard JSON document
 * generated by `buildAgentCard()` from @renseiai/agentfactory-server.
 *
 * The card advertises the agent's identity, capabilities, skills,
 * and authentication requirements per the A2A spec.
 */

import { NextResponse } from 'next/server'
import { buildAgentCard, createLogger } from '@renseiai/agentfactory-server'
import type { A2aServerConfig } from '@renseiai/agentfactory-server'

const log = createLogger('api:a2a:agent-card')

export type { A2aServerConfig }

/**
 * Configuration for the agent-card route handler.
 */
export interface AgentCardRouteConfig {
  /** A2A server configuration for AgentCard generation */
  a2aConfig: A2aServerConfig
}

/**
 * Create a GET handler for `/.well-known/agent-card.json`.
 *
 * @param config - Agent card configuration
 * @returns Next.js route handler
 */
export function createAgentCardHandler(config: AgentCardRouteConfig) {
  // Pre-build the card at factory time so it's not recomputed per request
  const card = buildAgentCard(config.a2aConfig)

  return async function GET() {
    try {
      return NextResponse.json(card, {
        status: 200,
        headers: {
          'Cache-Control': 'public, max-age=3600',
          'Content-Type': 'application/json',
        },
      })
    } catch (error) {
      log.error('Failed to serve agent card', { error })
      return NextResponse.json(
        { error: 'Internal Server Error', message: 'Failed to generate agent card' },
        { status: 500 }
      )
    }
  }
}
