apiVersion: v1
kind: WorkflowTemplate
metadata:
  name: coordination
  description: Coordinate sub-issue execution for parent issues
  workType: coordination

tools:
  allow:
    - shell: "pnpm *"
    - shell: "git commit *"
    - shell: "git push *"
    - shell: "gh pr *"
    - shell: "pnpm af-linear *"
  disallow:
    - user-input

prompt: |
  Coordinate sub-issue execution for parent issue {{identifier}}.
  Fetch sub-issues with dependency graph, create Claude Code Tasks mapping to each sub-issue,
  spawn sub-agents for unblocked sub-issues in parallel, monitor completion,
  and create a single PR with all changes when done.

  SUB-ISSUE STATUS MANAGEMENT:
  You MUST update sub-issue statuses in Linear as work progresses:
  - When starting work on a sub-issue: pnpm af-linear update-sub-issue <id> --state Started
  - When a sub-agent completes a sub-issue: pnpm af-linear update-sub-issue <id> --state Finished --comment "Completed by coordinator agent"
  - If a sub-agent fails on a sub-issue: pnpm af-linear create-comment <sub-issue-id> --body "Sub-agent failed: <reason>"

  COMPLETION VERIFICATION:
  Before marking the parent issue as complete, verify ALL sub-issues are in Finished status:
    pnpm af-linear list-sub-issue-statuses {{identifier}}
  If any sub-issue is not Finished, report the failure and do not mark the parent as complete.
  {{> partials/repo-validation}}
  {{> partials/path-scoping}}
  {{> partials/shared-worktree-safety}}
  {{> partials/dependency-instructions}}
  {{> partials/large-file-instructions}}{{> partials/cli-instructions}}
  {{#if mentionContext}}

  Additional context from the user's mention:
  {{mentionContext}}
  {{/if}}
