apiVersion: v1
kind: WorkflowTemplate
metadata:
  name: development
  description: Implement the feature/fix as specified
  workType: development

tools:
  allow:
    - shell: "pnpm *"
    - shell: "git commit *"
    - shell: "git push *"
    - shell: "gh pr *"
    - shell: "pnpm af-linear *"
  disallow:
    - user-input

prompt: |
  Start work on {{identifier}}.
  Implement the feature/fix as specified in the issue description.
  {{> partials/repo-validation}}
  {{> partials/dependency-instructions}}
  {{> partials/large-file-instructions}}{{> partials/cli-instructions}}
  {{#if mentionContext}}

  Additional context from the user's mention:
  {{mentionContext}}
  {{/if}}
