apiVersion: v1
kind: WorkflowTemplate
metadata:
  name: qa-coordination
  description: Coordinate QA across sub-issues for parent issues
  workType: qa-coordination

tools:
  allow:
    - shell: "pnpm *"
    - shell: "gh pr *"
    - shell: "pnpm af-linear *"
  disallow:
    - user-input

prompt: |
  Coordinate QA across sub-issues for parent issue {{identifier}}.

  WORKFLOW:
  1. Fetch sub-issues: {{linearCli}} list-sub-issues {{identifier}}
  2. Create Claude Code Tasks for each sub-issue's QA verification
  3. Spawn qa-reviewer sub-agents in parallel — no dependency graph needed, all sub-issues are already Finished
  4. Each sub-agent: reads sub-issue requirements, runs scoped tests, validates implementation, emits pass/fail
  5. Collect results — ALL sub-issues must pass QA for the parent to pass

  RESULT HANDLING:
  - If ALL pass: Emit <!-- WORK_RESULT:passed --> in your final message. The orchestrator will promote to Delivered.
  - If ANY fail: Post rollup comment listing per-sub-issue results. Emit <!-- WORK_RESULT:failed --> in your final message. The orchestrator will move the issue to Backlog for remediation.

  IMPORTANT CONSTRAINTS:
  - This is READ-ONLY validation — do NOT create PRs or make git commits
  - The PR already exists from the development coordination phase
  - Run {{packageManager}} test, {{packageManager}} typecheck, and {{packageManager}} build as part of validation
  - Verify each sub-issue's acceptance criteria against the actual code changes
  - NEVER manually change the parent issue status. The orchestrator manages all status transitions based on your WORK_RESULT marker.

  HARD FAIL RULE — BUILD FAILURES:
  If `{{packageManager}} typecheck` or `{{packageManager}} build` exits with a non-zero exit code, you MUST report <!-- WORK_RESULT:failed --> immediately.
  Do NOT rationalize, skip, or explain away build/typecheck failures (e.g., "will resolve on merge").
  A failing build is an automatic QA failure regardless of any other results.

  {{> partials/work-result-marker}}
  {{> partials/shared-worktree-safety}}
  {{> partials/dependency-instructions}}
  {{> partials/large-file-instructions}}{{> partials/cli-instructions}}
  {{#if mentionContext}}

  Additional context from the user's mention:
  {{mentionContext}}
  {{/if}}
