/**
 * Agent Inbox Module
 *
 * Valkey Streams-based agent inbox with two priority lanes (urgent/normal).
 * Replaces pending-prompts.ts Redis Lists with durable, consumer-group-backed streams.
 *
 * Stream keys:
 *   agent:inbox:{agentId}:urgent  — stop signals, user directives
 *   agent:inbox:{agentId}:normal  — hook results, nudges
 *
 * Consumer group: inbox-readers
 * Consumer name: worker:{workerId}
 *
 * Key rule: Inbox messages do NOT trigger work assignments (Rule 1 from SUP-1163).
 * Workers pull messages on their own poll schedule.
 */

import { getRedisClient, isRedisConfigured } from './redis.js'
import { createLogger } from './logger.js'

const log = createLogger('agent-inbox')

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const URGENT_SUFFIX = ':urgent'
const NORMAL_SUFFIX = ':normal'
const STREAM_PREFIX = 'agent:inbox:'
const ARCHIVE_PREFIX = 'agent:inbox:archive:'
const CONSUMER_GROUP = 'inbox-readers'
const DEFAULT_MAX_LEN = 1_000
const ARCHIVE_TTL_SECONDS = 7 * 24 * 60 * 60 // 7 days

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type InboxMessageType = 'stop' | 'directive' | 'hook-result' | 'nudge'
export type InboxLane = 'urgent' | 'normal'

export interface InboxMessage {
  /** Stream entry ID (auto-generated by XADD) */
  id: string
  /** Message type determines routing behavior */
  type: InboxMessageType
  /** Session this message belongs to */
  sessionId: string
  /** The actual message content */
  payload: string
  /** Optional user ID (for directives) */
  userId?: string
  /** Optional user display name */
  userName?: string
  /** Unix timestamp ms */
  createdAt: number
  /** Which lane this message came from */
  lane: InboxLane
}

// Input type omits auto-generated fields
type InboxMessageInput = Omit<InboxMessage, 'id' | 'lane'>

// ---------------------------------------------------------------------------
// Key builders
// ---------------------------------------------------------------------------

function urgentKey(agentId: string): string {
  return `${STREAM_PREFIX}${agentId}${URGENT_SUFFIX}`
}

function normalKey(agentId: string): string {
  return `${STREAM_PREFIX}${agentId}${NORMAL_SUFFIX}`
}

function archiveUrgentKey(agentId: string, sessionId: string): string {
  return `${ARCHIVE_PREFIX}${agentId}:${sessionId}${URGENT_SUFFIX}`
}

function archiveNormalKey(agentId: string, sessionId: string): string {
  return `${ARCHIVE_PREFIX}${agentId}:${sessionId}${NORMAL_SUFFIX}`
}

function consumerName(workerId: string): string {
  return `worker:${workerId}`
}

// ---------------------------------------------------------------------------
// Consumer group management
// ---------------------------------------------------------------------------

// Track which streams have had their consumer group created
const groupsCreated = new Set<string>()

/**
 * Ensure the consumer group exists on a stream. Idempotent.
 * Uses MKSTREAM to create the stream if it doesn't exist.
 */
export async function ensureConsumerGroup(agentId: string): Promise<void> {
  if (!isRedisConfigured()) return

  const redis = getRedisClient()
  const keys = [urgentKey(agentId), normalKey(agentId)]

  for (const key of keys) {
    if (groupsCreated.has(key)) continue

    try {
      await redis.xgroup('CREATE', key, CONSUMER_GROUP, '0', 'MKSTREAM')
    } catch (err: unknown) {
      if (err instanceof Error && !err.message.includes('BUSYGROUP')) {
        throw err
      }
    }
    groupsCreated.add(key)
  }
}

// ---------------------------------------------------------------------------
// Publish
// ---------------------------------------------------------------------------

/**
 * Publish a message to the urgent lane (stop signals, user directives).
 * @returns The stream entry ID
 */
export async function publishUrgent(
  agentId: string,
  message: InboxMessageInput,
): Promise<string> {
  return publish(agentId, 'urgent', message)
}

/**
 * Publish a message to the normal lane (hook results, nudges).
 * @returns The stream entry ID
 */
export async function publishNormal(
  agentId: string,
  message: InboxMessageInput,
): Promise<string> {
  return publish(agentId, 'normal', message)
}

async function publish(
  agentId: string,
  lane: InboxLane,
  message: InboxMessageInput,
): Promise<string> {
  if (!isRedisConfigured()) {
    throw new Error('Redis not configured — cannot publish to agent inbox')
  }

  await ensureConsumerGroup(agentId)

  const redis = getRedisClient()
  const key = lane === 'urgent' ? urgentKey(agentId) : normalKey(agentId)
  const payload = JSON.stringify(message)

  const id = await redis.xadd(
    key,
    'MAXLEN',
    '~',
    String(DEFAULT_MAX_LEN),
    '*',
    'data',
    payload,
  )

  if (!id) {
    throw new Error(`XADD returned null for ${key} — stream write failed`)
  }

  log.info('Inbox message published', {
    agentId,
    lane,
    type: message.type,
    sessionId: message.sessionId,
    streamId: id,
  })

  // Fire-and-forget Pub/Sub nudge for urgent messages
  if (lane === 'urgent') {
    redis.publish(`agent:nudge:${agentId}`, 'urgent').catch(() => {
      // Pub/Sub is advisory — ignore failures
    })
  }

  return id
}

// ---------------------------------------------------------------------------
// Consume (urgent-first)
// ---------------------------------------------------------------------------

/**
 * Read messages from the agent's inbox, checking urgent lane first.
 * Returns urgent messages first; only reads normal if urgent is empty.
 *
 * Uses XREADGROUP so messages are tracked as pending until ACKed.
 */
export async function readInbox(
  agentId: string,
  workerId: string,
  count: number = 10,
): Promise<InboxMessage[]> {
  if (!isRedisConfigured()) return []

  await ensureConsumerGroup(agentId)

  // Read urgent first
  const urgentMessages = await readLane(agentId, 'urgent', workerId, count)
  if (urgentMessages.length > 0) {
    return urgentMessages
  }

  // Only check normal if urgent is empty
  return readLane(agentId, 'normal', workerId, count)
}

async function readLane(
  agentId: string,
  lane: InboxLane,
  workerId: string,
  count: number,
): Promise<InboxMessage[]> {
  const redis = getRedisClient()
  const key = lane === 'urgent' ? urgentKey(agentId) : normalKey(agentId)
  const consumer = consumerName(workerId)

  try {
    const results = await redis.xreadgroup(
      'GROUP',
      CONSUMER_GROUP,
      consumer,
      'COUNT',
      String(count),
      'STREAMS',
      key,
      '>', // only new messages
    )

    if (!results || (results as unknown[]).length === 0) {
      return []
    }

    const messages: InboxMessage[] = []
    for (const [, entries] of results as Array<[string, Array<[string, string[]]>]>) {
      for (const [id, fields] of entries) {
        const parsed = parseStreamMessage(id, fields, lane)
        if (parsed) {
          messages.push(parsed)
        } else {
          // Malformed message — ack and skip
          await ack(agentId, lane, id)
          log.warn('Skipped malformed inbox message', { agentId, lane, streamId: id })
        }
      }
    }

    return messages
  } catch (err) {
    log.error('Failed to read inbox lane', { error: err, agentId, lane })
    return []
  }
}

// ---------------------------------------------------------------------------
// Acknowledge
// ---------------------------------------------------------------------------

/**
 * Acknowledge a message after successful delivery.
 * Removes it from the consumer's pending entries list.
 */
export async function ack(
  agentId: string,
  lane: InboxLane,
  messageId: string,
): Promise<void> {
  if (!isRedisConfigured()) return

  const redis = getRedisClient()
  const key = lane === 'urgent' ? urgentKey(agentId) : normalKey(agentId)

  await redis.xack(key, CONSUMER_GROUP, messageId)

  log.debug('Inbox message acknowledged', { agentId, lane, messageId })
}

// ---------------------------------------------------------------------------
// Archive (non-destructive cleanup on session completion)
// ---------------------------------------------------------------------------

/**
 * Archive inbox streams for a completed session.
 * Renames stream keys to archived namespace with TTL for automatic cleanup.
 * ACKs all pending messages before archiving.
 */
export async function archiveInbox(
  agentId: string,
  sessionId: string,
): Promise<void> {
  if (!isRedisConfigured()) return

  const redis = getRedisClient()

  const lanes: Array<{ src: string; dst: string }> = [
    { src: urgentKey(agentId), dst: archiveUrgentKey(agentId, sessionId) },
    { src: normalKey(agentId), dst: archiveNormalKey(agentId, sessionId) },
  ]

  for (const { src, dst } of lanes) {
    try {
      // Check if the stream exists
      const exists = await redis.exists(src)
      if (!exists) continue

      // ACK all pending messages before archiving
      await ackAllPending(agentId, src)

      // Rename to archive namespace
      await redis.rename(src, dst)

      // Set TTL for automatic cleanup
      await redis.expire(dst, ARCHIVE_TTL_SECONDS)

      log.info('Inbox stream archived', { agentId, sessionId, from: src, to: dst })
    } catch (err) {
      log.error('Failed to archive inbox stream', {
        error: err,
        agentId,
        sessionId,
        stream: src,
      })
    }
  }

  // Clear consumer group tracking for this agent so it gets re-created for next session
  groupsCreated.delete(urgentKey(agentId))
  groupsCreated.delete(normalKey(agentId))
}

/**
 * ACK all pending messages in a stream's consumer group.
 */
async function ackAllPending(agentId: string, streamKey: string): Promise<void> {
  const redis = getRedisClient()

  try {
    // Read pending entries summary
    const pending = await redis.xpending(streamKey, CONSUMER_GROUP)

    if (!pending || !Array.isArray(pending) || (pending[0] as number) === 0) {
      return
    }

    const minId = pending[1] as string
    const maxId = pending[2] as string

    if (!minId || !maxId) return

    // Get all pending message IDs
    const entries = await redis.xpending(
      streamKey,
      CONSUMER_GROUP,
      minId,
      maxId,
      '1000',
    )

    if (!entries || !Array.isArray(entries)) return

    for (const entry of entries as Array<[string, string, number, number]>) {
      const messageId = entry[0]
      await redis.xack(streamKey, CONSUMER_GROUP, messageId)
    }
  } catch (err) {
    log.warn('Failed to ack pending messages before archive', {
      error: err,
      agentId,
      stream: streamKey,
    })
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse a stream entry's fields array into an InboxMessage.
 * Fields come as [key1, val1, key2, val2, ...] from XREADGROUP.
 */
function parseStreamMessage(
  id: string,
  fields: string[],
  lane: InboxLane,
): InboxMessage | null {
  try {
    for (let i = 0; i < fields.length; i += 2) {
      if (fields[i] === 'data') {
        const data = JSON.parse(fields[i + 1]) as InboxMessageInput
        return {
          ...data,
          id,
          lane,
        }
      }
    }
    return null
  } catch {
    return null
  }
}

// Re-export key constants for use by other modules
export {
  CONSUMER_GROUP as INBOX_CONSUMER_GROUP,
  ARCHIVE_TTL_SECONDS as INBOX_ARCHIVE_TTL_SECONDS,
}
